### ISSUE TITLE
[epic] Docker cloud deploy of the basic stack

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#1]
As an Admin I want to deploy the entire application stack in an automated fashion so that it is live in under 5 minutes

* Key config:
  * base domain e.g. "datahub.io"
  * stage e.g. "staging", "testing", "production" ("" as url)
* Misc credentials
  * Docker cloud credentials 
  * S3 credentials

## Acceptance criteria

* [x] We can launch a new app instance with one or a few commands
* [ ] We can destroy an app instance with one or a few commands

## Tasks

* [x] auth service
  * [x] postgres service
  * [x] auth webapp deployed
    * [x] config and linked to postgres service
    * [x] Set `EXTERNAL_ADDRESS` variable
      * [x] nice url (via cloudflare) - note this is not actually need because we really should route this into a unified API but it is a way to test this stuff to start with
      * [x] https works *switch from full to flexible on cloudflare and expose port 443 on the webserver*
      * [x] Set `EXTERNAL_ADDRESS` variable
* [x] frontend
* [x] API frontend / proxy service - nginx proxy (cf openspending)
* [x] rawstore service
* [x] Wrap this into a nice command
  * [x] Move env variables in env.template with instructions on how to copy and edit and then use so that we can commit the docker-cloud.yml without including sensitive information (Note docker will use local env variables of the same name)

## Analysis

We are using docker cloud stacks which are similar to compose files (but a little different).

Service discovery: https://docs.docker.com/docker-cloud/apps/service-links/

**Comment by zelima** [comment]
FIXED. Most of this is done, only destroy is remaining. 
Follow up here https://github.com/datahq/deploy/issues/10
