### ISSUE TITLE
Create function to create users with token

### ISSUE THREAD

**Issue by Mikanebu** [datahq/deploy#12]
We want to have a script in python3 to create users. 

## Acceptance criteria

* [x] Can create a user from command line (and outputs token)
* [x] Can generate a token for user (assume the user exists)

## Tasks

* [x] Connect to DB, create user
* [x]  Generate token [and do what ...]

> What is `DP` ~rufuspollock

> And i've tidied your sample script below

```
# get connection string from environment
...

# create the user in the database
insert into users values (‘core’, ‘core’, ‘core’, ‘Core Datasets’, ‘datasets@okfn.org’, ‘’, ‘’)
# check it worked (optional)
# select * from users;

token = jwt.encode(token, private_key, algorithm='RS256').decode('ascii')
```

**Comment by Mikanebu** [comment]
FIXED
