### ISSUE TITLE
setting up dns automatically using cloudflare api

### ISSUE THREAD

**Issue by zelima** [datahq/deploy#13]
As an Admin I want to set all needed DNS for my application automatically with script, using CloudFlare API

## Acceptance criteria 

* [ ] No more manual setup with CloudFlare wizard 

## Tasks 

* [ ] take a look at CloudFlare API
* [ ] add function handling dns setup to main.py 
* [ ] test if possible
