### ISSUE TITLE
Test all the services in the consistent way

### ISSUE THREAD

**Issue by Mikanebu** [datahq/deploy#15]
We currently have 5 repos (+ deploy) (in Python) with several different ways of running tests.

# Acceptance criteria

- [ ] deploy is tested with tox

Bonus:

- [ ] able to install with pip 
- [ ] we have Makefile for test and install  
- [ ] versioned

# Tasks 

- [ ] refactor tests for deploy
- [ ] update README

**Comment by Mikanebu** [comment]
WONTFIX
