### ISSUE TITLE
deploy metastore to docker 

### ISSUE THREAD

**Issue by zelima** [datahq/deploy#17]
we need [metastore](https://github.com/datahq/metastore) on docker so that we could perform searches. 

## Acceptance Criteria

* [ ] metastore is working together with elastiseach service on docker

## Tasks

* [ ] add metastore to stackfile
* [ ] add ealsticsearch to stackfile
* [ ] test deaployed (search something Eg: /metastore/search?owner=core)

# Analysis

Tried to start ES service on docker but we are out of memory. @rufuspollock we probbaly need to upgrade Node (cluster) size 

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000000008a660000, 1973026816, 0) failed; error='Cannot allocate memory' (errno=12)
There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 1973026816 bytes for committing reserved memory.
An error report file with more information is saved as:
/tmp/hs_err_pid1.log
```
