### ISSUE TITLE
Create datahub s3 buckets

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#2]
## Acceptance criteria

* [x] Create the s3 datahub user with relevant permissions (and message me keys)
* [ ] Create the buckets:
  * raw: rawstore.datahub.io, rawstore-testing.datahub.io
  * pkg: pkgstore.datahub.io, pkgstore-testing.datahub.io 

And we need to add CORs. May want to reinstate the automation code for this in the deploy ...

## Tasks

* [x] Create the user with permissions to create, read, write, change permissions on buckets
* [x] Add back into the new main.py the code for creating buckets from [old main.py][old] (with bucket names as appropriate for the stage and domain)
  * [x] Add config to .env.template for this e.g. OBJECT_STORAGE_ACCESS_KEY etc
  * [x] CORs set
  * [x] Reinstate the test
* [x] Create the buckets using this script
* [x] Use this config for the relevant services that need it e.g. rawstore, assembler

[old]: https://github.com/datahq/deploy/blob/3a9bb8afa99b521b0ded816c28ffd47e028d6f4a/main.py

Config will have

```
OBJECT_STORAGE_ACCESS_KEY
OBJECT_STORAGE_SECRET_KEY
RAWSTORE_BUCKET_NAME
PACKAGESTORE_BUCKET_NAME
```

**Comment by zelima** [comment]
FXIED
