### ISSUE TITLE
Configure google oauth for login 

### ISSUE THREAD

**Issue by zelima** [datahq/deploy#27]
Currently, we are using same credentials for Testing and Productions. We need another pair of `GOOGLE_KEY`, `GOOGLE_SECRET`

## Acceptance Criteria

* [ ] Production and Testing are separate

## Tasks

* [ ] Create new google 0auth app with new credentials
* [ ] update stack files
* [ ] redeploy

**Comment by rufuspollock** [comment]
@zelima these don't need to separate I think (i'm not sure there is any great security risk here atm). Having them share the same key isn't an issue in terms of config.

**Comment by zelima** [comment]
WONTFIX as suggested above not needed for now
