### ISSUE TITLE
Disable google login option on production

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#28]
We'll go for github only for now.

Why?

* Simplicity - no risk of users getting confused
* We get a consistent username

## Tasks

* [x] Remove Google OAUTH from docker config
* [x] Remove in local env.production
* [ ] Remove in frontend (separate item for @anuveyatsu )

**Comment by zelima** [comment]
@anuveyatsu they are removed from config.

**Comment by rufuspollock** [comment]
FIXED. Frontend fix will be separate.
