### ISSUE TITLE
stats method to report system stats

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#30]
We want to have functions to return total users and total datasets, and users registered in last day. 

## Acceptance criteria

* [x] total number of users in db, plus number registered in last day - direct access to user db
* [x] total number of datasets (via metastore search API)
* [x] this info can then get added to a tracking spreadsheet - https://docs.google.com/spreadsheets/d/1_rUBr0-nfo2zJdcA5DQ0MNqoWZq0djmokvHDYbu_gQA/edit#gid=0

# Tasks: 
* [x] create function `users_total` - get directly from DB
* [x] create function `users_last_day` - get directly from DB
* [x] create function `datasets_total` - API call to metastore
* [x] update abovementioned spreadsheet everyday in the morning

**Comment by Mikanebu** [comment]
FIXED
