### ISSUE TITLE
AUTHORIZEDKEYS service is not running

### ISSUE THREAD

**Issue by Mikanebu** [datahq/deploy#32]
If we do not use this service, I suggest to remove from docker cloud and `stackfile`, so our status will change from `partially running` to `running`

## Acceptance criteria

* [x] there is no more `Authorizedkeys` service in `stackfile`

## Tasks

* [x] remove `Authorizedkeys` from docker cloud, and stackfile will be automatically updated
* [x] remove `Authorizedkeys` service from the `docker-cloud.yml`

**Comment by zelima** [comment]
@Mikanebu this should not take more than couple minutes. could you please estimate add to milestone and fix it.

**Comment by Mikanebu** [comment]
@zelima How about `docker-cloud.yml` in `deploy` repo, it has this service in the list

**Comment by zelima** [comment]
@Mikanebu I thought this issue was about removing that from stack file

**Comment by Mikanebu** [comment]
@zelima then, when we redeploy it by our script, it will create another `AuthorizedKeys` service

**Comment by zelima** [comment]
@Mikanebu sorry was not clear enough - yes, we should remove it from docker-cloud.yml as well

**Comment by Mikanebu** [comment]
FIXED
