### ISSUE TITLE
Script for auto creation of secrets

### ISSUE THREAD

**Issue by zelima** [datahq/deploy#59]
As an admin I want to update secrets easily, with one command and predefined `.env` file, so that I do not have to know about kubernetes, or kubectl

## Acceptance criteria

* [x] able to update secrets with one command

## Tasks

* [x] create `.env.template` 
* [x] write the script to run appropriate `kubectl` command
* [x] update README

**Comment by zelima** [comment]
FIXED
