### ISSUE TITLE
Reintroduce site testing code

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#7]
We need a way to test deployments that they are running OK without having to manually a) login to docker cloud b) look at the site.

## Acceptance Criteria

* [x] All the command exist and work

## Tasks

* [x] docker check
* [x] api check (auth and metastore only)
  * [ ] auth returns something like we expet
  * [x] search returns something
* [x] frontend test
  * [x] front page 200
  * [x] shwocase page 200
* [x] better frontend tests (?)

# Analysis

At the moment it looks like this:

* Run a deploy (or upgrade)
* Login to docker cloud to see all services are running ok
  * check status is ok for all services in the relevant stack
* Visit various APIs (try to remember which ones actually work without auth!)
  * /auth/check
  * /metastore/search?q="finance"
  * ~~/rawstore/upload~~ - does not work without auth
* Visit the website
  * front page
  * showcase page e.g. /core/finance-vix/
  * (profile page e.g. /core)

OK for website =

* 200
* assert some content is there
* could check page content against cached version (?) - snapshot testing

CLI

```python=
python main.py check
python main.py check_docker
python main.py check_apis
python main.py check_frontend
```

**Comment by Mikanebu** [comment]
FIXED

**Comment by rufuspollock** [comment]
Need:

* Documentation in README of extra config variables to use
* docker stuff should use docker-cloud CLI by default i think (unless we want to generally switch to API - which is possible but everyone already has docker-cloud CLI)
  * docker just needs to check the stack for now (no need to check each service but you can if you want)
* frontend and api should make jwt_token optional (just skip tests that need that if not available)
* `check` command that runs all 3 in order

**Comment by Mikanebu** [comment]
FIXED
