### ISSUE TITLE
Tidy up RDS env variables

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#9]
Tidy up RDS environment variables

## Tasks

* [x] Remove from .env.template following vars so that we we don't duplicate RDS_DATABASE_URI.
:

```
RDS_DATABASE_USERNAME=${PROJECT}
RDS_DATABASE_PASSWORD=
```
   And just prompt user on creation of DB.
* [ ] change `RDS_DATABASE_URI` to `RDS_URI` and add a comment explaining what it is in the env file
* [x] change postgres to postgresql in RDS_URI

**Comment by zelima** [comment]
FIXED
